/* eu: 0 */
/* src: 2024-02-14 14:32:08 GMT */
/* gen: 2024-02-16 14:59:56 GMT */
;(function(){(function(){function da(a,b,c,m){b||(b=function(){});m||(m=function(){});c=c||v;var k=J("script",c);k.setAttribute("type","text/javascript");k.setAttribute("src",a);k.setAttribute("async","async");t(k)&&(ea?k.onreadystatechange=function(){"loaded"==this.readyState||"complete"==this.readyState?A(b):A(m)}:(k.onload=function(q){var p=this;A(function(){b.call(p,q);p.parentNode.removeChild(p)})},k.onerror=function(q){var p=this;A(function(){m.call(p,q);p.parentNode.removeChild(p)})}),Y(c).appendChild(k))}
function y(){return{state:function(){return e.state.s},K:function(){return e.google.Y},pa:function(){return e.W.N}}}function Z(){var a=!1;if(null!==P)return P;if(g===g.top)a=g.location;else try{a=g.top.location.href?g.top.location:!1}catch(b){B(g.__lxG__.pageUrl)?a=aa(g.__lxG__.pageUrl):v.referrer?a=aa(v.referrer):a=g.location}return a?P={href:a.href,host:a.host,hostname:a.hostname,origin:a.origin,pathname:a.pathname,port:a.port,protocol:a.protocol,hash:a.hash,search:a.search}:!1}function aa(a){var b=
J("a");b.href=a;return b}function Q(a){if((a||0===a)&&"function"==typeof K[a]){var b=K[a];delete K[a];b()}}function A(a,b){null===R&&(R=t(g.MessageChannel));null===S&&(S=t(g.MutationObserver));null===T&&(T="function"===typeof g.queueMicrotask);null===U&&(U="function"===typeof g.Promise,ba=Promise.resolve());null===L&&(L="function"===typeof g.requestAnimationFrame);null===V&&(V="function"===typeof g.requestIdleCallback);b=t(b)?b:{};var c=!1,m=!1,k=!1;L||!0!==b.T||(b.T=!1,b.A=!0);a=K.push(a)-1;var q=
function(p){return function(w){Q(p,w)}}(a);V&&!0===b.l?g.requestIdleCallback(function(){q("requestIdleCallback")}):!0===b.T?g.requestAnimationFrame(function(){q("requestAnimationFrame")}):b.A?setTimeout(function(){q("setTimeout")},isNaN(b.A)?0:1*b.A):(!0!==b.l&&(T?(k=!0,g.queueMicrotask(function(){q("queueMicrotask")})):U?(m=!0,ba.then(function(){q("promiseResolve")}).catch(function(p){throw p;})):S&&(c=fa(a))),c||m||k||(R?ha(a):L?g.requestAnimationFrame(function(){q("requestAnimationFrame")}):setTimeout(function(){q("setTimeout")},
0)))}function fa(a){var b=null;if(F.length)for(var c=0,m=F.length;c<m;c++)if(F.hasOwnProperty(c)&&""===F[c].data){b=F[c];break}if(!b)if(100>F.length)b={data:"",node:v.createTextNode("")},F.push(b),(new MutationObserver(function(){Q(b.data,"MutationObserver");b.data=""})).observe(b.node,{characterData:!0});else return!1;b.data=a;b.node.data=a;return!0}function ha(a){M||(M=new MessageChannel,M.port2.onmessage=function(b){Q(b.data,"MessageChannel")});M.port1.postMessage(a)}function W(){var a=null;W=
function(){if(null===a){a=!1;try{var b=Object.defineProperty({},"passive",{get:function(){a=!0}});g.addEventListener("testPassive",null,b);g.removeEventListener("testPassive",null,b)}catch(c){}}return a};return W()}function N(a){var b={};N=function(c){if(!t(b[c])){c=c.split("+").join(" ");for(var m={},k=("?"===c[0]||"#"===c[0]?c.substr(1):c).split("&"),q=0;q<k.length;q++){var p=k[q].split("="),w=p[0];p=p[1]||"";try{w=decodeURIComponent(w)}catch(u){w=unescape(w)}try{p=decodeURIComponent(p)}catch(u){p=
unescape(p)}m[w]=p}b[c]=m}return b[c]};return N(a)}function O(a){a=parseInt(a,10);return isNaN(a)?0:a}function Y(a){a=a||v;var b=a.documentElement;var c=a||v;if(c=c.getElementsByTagName("head")[0])return c;for(c=b.firstChild;c&&"#text"==c.nodeName.toLowerCase();)c=c.nextSibling;if(c&&"#text"!=c.nodeName.toLowerCase())return c;a=J("head",a);b.appendChild(a);return a}function t(a){return"undefined"!=typeof a}function B(a,b){b=t(b)?b:!1;return t(a)?a:b}function ia(a,b){x(b,function(c){a[c]=b[c]})}function x(a,
b){for(var c in a)if(a.hasOwnProperty(c)&&"length"!==c&&!1===b.call(a[c],c,a[c]))break}function ja(a,b){for(var c=0;c<a.length&&(!a.hasOwnProperty(c)||"length"===c||!1!==b.call(a[c],c,a[c]));c++);}function ka(a,b,c,m){m=m||!1;if(a){"[object NodeList]"==Object.prototype.toString.call(a)||la(a)||(a=[a]);var k=b.split(" ");x(a,function(q){a[q]&&x(k,function(p){k[p]&&(a[q].addEventListener?a[q].addEventListener(k[p],c,m):a[q].attachEvent("on"+k[p],c))})})}}function ma(a,b,c){if(a){"[object NodeList]"!=
Object.prototype.toString.call(a)&&(a=[a]);var m=b.split(" ");b=m.length;var k;for(k=0;k<b;k++)x(a,function(){this.detachEvent?this.detachEvent("on"+m[k],c):(this.removeEventListener(m[k],c,!0),this.removeEventListener(m[k],c))})}}function J(a,b){b=b||v;return b.createElement(a)}function X(a,b,c){c=c||v;b=b||na;var m=J("script",c);m.type="text/javascript";if(t(a.src)&&a.src)m.src=a.src,m.className=a.className;else{var k=a.text||a.textContent||a.innerHTML||"";m.className=a.className;m.appendChild(c.createTextNode(k))}!0===
b?(a.parentNode.insertBefore(m,a.nextSibling),a.parentNode&&a.parentNode.removeChild(a)):b.appendChild(m)}var v=document,g=window,ca=v.documentElement,na=Y(),C=navigator.userAgent.toLowerCase();C.match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/);var D=/opera/.test(C),ea=/msie/.test(C)&&!D;g.__lxG__=g.__lxG__||{};C=Object.create;"function"!==typeof C&&(C=function(a){function b(){}b.prototype=a;return new b});var la=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)};B(g.__lxG__.onscrl_ease,
30);var M=!1,F=[],K=[],ba=null,R=null,S=null,L=null,V=null,T=null,U=null,P=null;(function(){function a(){t(v.body)&&v.body&&ma(v,"DOMContentLoaded",a)}function b(){t(v.body)&&v.body||A(b,{A:!0})}ka(v,"DOMContentLoaded",a,W()?{passive:!0}:!1);b()})();C=/__lxG(\d+?)__/im.exec("__lxG223031__consent__")[1];var oa=!1,pa=function(){function a(d){t(Object.defineProperty)?Object.defineProperty(f[d].i,"push",{configurable:!0,enumerable:!1,writable:!0,
value:function(){var h=arguments;h=Array.prototype.push.apply(this,h);c(d);return h}}):H||(H=setTimeout(b,25))}function b(){x(f,function(d){c(d)});setTimeout(b,25)}function c(d){f[d].h&&!f[d].G&&f[d].i.length>f[d].L+1&&(f[d].G=!0,f[d].C?m(d):A(function(){m(d)}))}function m(d){ja(f[d].i,function(h){if(h>f[d].L){f[d].L=h;var n=f[d].i[h];f[d].o&&(n=function(){f[d].o(f[d].i[h])});if(f[d].C)try{n()}catch(l){}else A(n,{l:f[d].l})}});f[d].G=!1}function k(d,h){if(t(f[d]))return f[d].O.push(h)}function q(d){t(f[d])&&
x(f[d].O,function(h,n){G[n].H||p(n)})}function p(d){if(!t(G[d])||G[d].H)return!1;d=G[d];var h=!0;x(d.V,function(n,l){if(!B(f[l].h))return h=!1});h&&(d.H=!0,f[d.V[0]].i.push(d.Z))}function w(d){t(f[d])&&!f[d].h&&(f[d].h=!0,c(d),q(d))}function u(d,h,n){var l=[].slice.call(h);if(l.length){var r=[d],z=G.push({V:r,Z:n,H:!1})-1;k(r,z);x(l,function(E){E=l[E].la();r.push(E);k(E,z)});p(z)}else f[d].i.push(n)}var f=[],G=[],H=null;return function(d){d=d||{};var h={j:[],o:null,h:!1,C:!1,l:!1};ia(h,d);var n=null;
if(B(h.j.enqueued)){x(f,function(r){if(f[r].i===h.j)return n=r,!1});if(n)return f[n].X;n=h.j;h.j=[]}t(Object.defineProperty)?Object.defineProperty(h.j,"enqueued",{enumerable:!1,configurable:!1,writable:!1,value:"static"}):h.j.enqueued=!0;var l=f.length;f.push({id:l,i:h.j,O:[],L:-1,h:!1,C:h.C,G:!1,o:h.o,l:h.l});a(l);f[l].X={la:function(){return l},start:function(){w(l)},stop:function(){t(f[l])&&f[l].h&&(f[l].h=!1)},wb:function(){var r=t(f[l])?f[l].h:!1;return r},add:function(r){f[l].i.push(r)},za:function(){var r=
[].slice.call(arguments),z=r.pop();u(l,r,z)},Aa:function(r,z){u(l,r,z)}};h.h?w(l):n&&n.push(function(){w(l)});return f[l].X}}();(function(a){a=a||10;if(10<a){for(var b="",c=10;0<a;)b+=Math.round(Math.pow(36,c+1)-Math.random()*Math.pow(36,c)).toString(36).slice(1),a-=c,a<c&&(c=a);return b}return Math.round(Math.pow(36,a+1)-Math.random()*Math.pow(36,a)).toString(36).slice(1)})(5);var e={I:"__lxG__consent__",J:"consentQueue",Xa:"messageControl",Va:"messageControl",Wa:!0,U:"ver",Ha:63,B:{getState:"getState",
ma:"getPurposeOneAllowed",ka:"getGoogleConsentMode",qa:"showConsent"},Ua:"consentApi",ib:{Na:"cl-consent",nb:"cl-paywall"},g:{tagName:"script",ta:"type",ua:"text/clickiocmp",S:"clickio-cmp-",aa:"json",ea:"purpose-consent",ha:"special-feature-consent",fa:"purpose-li",ia:"vendor-consent",ja:"vendor-li",ca:"other-vendor-consent",da:"other-vendor-li",P:"paywall-logged-in",R:"paywall-subscribed",ba:"gdpr",ga:","},Ia:{s:-2,M:-1,kb:0,Ga:1,Ba:2},state:{s:null,M:-1,F:0,wa:1,Ta:2},google:{F:0,Ca:1,Y:2,sb:3,
fb:4},na:{F:0,N:1},W:{F:0,N:1},Kb:{M:0,xa:1,rb:2},Pa:{Ea:"v2",Ra:"_daisybit",Za:"_gdaisybit",$:"_clickiopw"},m:{google:755},v:{all:[1,2,3,4,5,6,7,8,9,10,11],Ma:[1,3,4,5,6],u:1},Fb:{Ka:561600,Lb:28800,Mb:1440,mb:43200},timeout:{Db:2E3,Eb:50},zb:{qb:"purpose",vendor:"vendor",Oa:"consents",eb:"legitimateInterests",pb:"publisher",tb:"restrictions"},$:{Jb:"user",Hb:"udata_ttl",Gb:{domain:"domain",vb:"site_id",status:"status",yb:"subscription_status",xb:"subscription_expires",Cb:"token"},sa:{Nb:"active",
jb:"missing"},Da:{gb:"login",hb:"logout",ya:"account"},ob:{close:0,Bb:1,Ab:2},Ib:{ub:{status:"status",data:"data"},sa:{Ya:"ok",error:"failed"}}}};e.Fa={cb:[[e.v.u],[],[e.m.google],[]],bb:[[e.v.u,3,4],[2,7,9,10],[e.m.google],[e.m.google]],ab:[[e.v.u],[2,7,9,10],[e.m.google],[e.m.google]],$a:[[],[2,7,9,10],[],[e.m.google]],na:[[e.v.u],[],[],[]],W:[[e.v.u],[],[],[]],Ja:{pending:null,lb:!0,Sa:!1}};D=function(){function a(u){u={detail:{state:u,google:y().K()}};if("function"===typeof g.CustomEvent)return new CustomEvent("clickioConsentEvent",
u);var f=v.createEvent("CustomEvent");f.initCustomEvent("clickioConsentEvent",!0,!1,u.detail);return f}function b(){function u(h,n){return(f(h,n)||"").split(e.g.ga).map(function(l){return""!==l?O(l):null}).filter(function(l){return~H.indexOf(n)||null===l?null!==l:0<l})}function f(h,n){n=(e.g.S+n).replace(/-(.)/g,function(l,r){return r.toUpperCase()});return B(h.dataset[n],null)}var G=v.querySelectorAll(e.g.tagName+"["+e.g.ta+'="'+e.g.ua+'"][async]'),H=[];H.push(e.g.P);H.push(e.g.R);x(G,function(h,
n){if(h=B(n.dataset[e.g.S+e.g.aa]))var l=JSON.parse(h);else{l={};var r=[e.g.ea,e.g.fa,e.g.ia,e.g.ja,e.g.ca,e.g.da,e.g.ha];r.push(e.g.P);r.push(e.g.R);x(r,function(E){l[r[E]]=u(n,r[E])})}var z=!1;x(l,function(E,qa){if(qa.length)return z=!0,!1});h=f(n,e.g.ba);z?null===h||O(h)&&y().state()!==e.state.s||!O(h)&&y().state():null!==h?O(h)?y().state()!==e.state.s&&X(n,!0):y().state()===e.state.s&&X(n,!0):X(n,!0)});if(!p)if(g.MutationObserver)p=new MutationObserver(function(h){var n=!1;x(h,function(l,r){if(r.addedNodes.length)return n=
!0,!1});n&&b(!0)}),p.observe(ca,{childList:!0,subtree:!0,attributes:!1,characterData:!1});else{var d=function(){p=setTimeout(d,250);b(!0)};d()}}function c(){c=function(){};m();pa({j:g.__lxG__[e.J],o:function(u){u(y().state(),y().K())},h:!0})}function m(){g.__lxG__[e.J]=g.__lxG__[e.J]||[]}g[e.I]=g[e.I]||{};var k=g[e.I];g.googletag=g.googletag||{};g.googletag.cmd=g.googletag.cmd||[];g.dataLayer=g.dataLayer||[];g.gtag=g.gtag||function(){window.dataLayer.push(arguments)};var q=g.gtag;var p;k[e.B.getState]=
function(){return y().state()};k[e.B.ka]=function(){return y().K()};k[e.B.ma]=function(){return y().pa()};var w={D:k,La:!1,Qa:function(){return!1},va:function(){var u=y().state();ca.dispatchEvent(a(u));t(k.consentCallback)&&A(function(f){return function(){k.consentCallback(f)}}(u));u!==e.state.M&&b()},oa:function(){m()},ra:c};if(oa)try{q("consent","default",{ad_storage:"granted",analytics_storage:"granted",functionality_storage:"granted",personalization_storage:"granted",security_storage:"granted",
ad_user_data:"granted",ad_personalization:"granted"})}catch(u){q("consent","update",{ad_storage:"granted",analytics_storage:"granted",functionality_storage:"granted",personalization_storage:"granted",security_storage:"granted",ad_user_data:"granted",ad_personalization:"granted"})}return w}();var I=function(a,b){var c=N(Z().search);t(c[a])?a=c[a]:(c=N(Z().hash),a=t(c[a])?c[a]:b||null);return a}("cl_consent_tool_version");if(I&&!B(g.__lxG__.consent_overload))return g.__lxG__.consent_overload=I,da("https://static.luxup.ru/t/consent_"+
C+"_"+I+".js"),!1;if(I&&"V4"!=I||B(D.D[e.U]))return!1;D.D[e.U]="V4";;t(g.__tcfapi)&&g.__tcfapi("setGdprApplies",2,function(){},!1);D.D[e.B.qa]=function(){return null};D.oa();D.ra();D.va()})();
})();